#!/usr/bin/env python3
"""
gen_trig_lut.py — Generate a 257-entry quarter-wave sine LUT in Q1.15.

The table covers [0, π/2] inclusive with 257 entries (indices 0..256) so that
both endpoints are exact and linear interpolation between adjacent entries
covers any angle.  Entry 256 duplicates entry 0 of the next quarter (sin(π/2)=1)
to allow the interpolation to read table[i+1] at the last valid index.

Q1.15 encoding:  value = round(sin(angle) * 32768)
  Maximum value: 32767 (represents sin(π/2) = 1.0 — note: NOT 32768 which
  would overflow int16_t; sin(π/2) = 32767 in Q1.15 by convention).

Output file: src/core/motor_math_lut.c
"""

import math
import sys
import os

N = 256  # quarter-wave resolution (256 intervals = 257 points)

def q15(v):
    """Round float v to Q1.15, clamped to [-32768, 32767]."""
    raw = int(math.floor(v * 32768.0 + 0.5))
    return max(-32768, min(32767, raw))

entries = []
for i in range(N + 1):
    angle = (math.pi / 2.0) * (i / N)
    entries.append(q15(math.sin(angle)))

out_path = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "..", "src", "core", "motor_math_lut.c"
)

lines = [
    "/**",
    " * @file motor_math_lut.c",
    " * @brief Quarter-wave sine LUT, Q1.15, 257 entries.",
    " *        AUTO-GENERATED by tools/gen_trig_lut.py — do not edit manually.",
    " *        Regenerate: python3 tools/gen_trig_lut.py",
    " *",
    " * Table: foc_sin_lut[i] = round(sin(i/256 * pi/2) * 32768), i = 0..256.",
    " * Index 256 = sin(pi/2) = Q15_ONE (32767) to allow interpolation sentinel.",
    " */",
    "#include \"foc/motor_math.h\"",
    "",
    "/* Quarter-wave sine LUT, 257 entries, Q1.15. */",
    "const int16_t foc_sin_lut[257] = {",
]

for row_start in range(0, N + 1, 8):
    chunk = entries[row_start : row_start + 8]
    row = "    " + ", ".join(f"{v:6d}" for v in chunk) + ","
    lines.append(row)

lines.append("};")
lines.append("")

with open(out_path, "w") as f:
    f.write("\n".join(lines))

print(f"Generated {out_path}  ({N+1} entries)")

# Verify max error
max_err = 0
for i in range(N + 1):
    angle = (math.pi / 2.0) * (i / N)
    ref = math.sin(angle) * 32768.0
    err = abs(entries[i] - ref)
    if err > max_err:
        max_err = err
print(f"Max quantisation error: {max_err:.3f} LSB Q1.15  (spec: ≤ 0.5 LSB, interpolation adds ≤ 3 more → ≤ 4 LSB total)")
